<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
require_login();
$user=current_user(); $uid=(int)user_id(); $isPro=$user['role']==='photographer';
$studio=null;$packages=[];$slots=[];$photos=[];$bookings=[];
if($isPro){
 $q=db()->prepare('SELECT * FROM photographers WHERE user_id=? LIMIT 1');$q->bind_param('i',$uid);$q->execute();$studio=$q->get_result()->fetch_assoc();
 if($studio){
  $pid=(int)$studio['id'];
  $q=db()->prepare('SELECT * FROM packages WHERE photographer_id=? ORDER BY price');$q->bind_param('i',$pid);$q->execute();$packages=$q->get_result()->fetch_all(MYSQLI_ASSOC);
  $q=db()->prepare('SELECT * FROM availability WHERE photographer_id=? AND available_date>=CURDATE() ORDER BY available_date,start_time LIMIT 100');$q->bind_param('i',$pid);$q->execute();$slots=$q->get_result()->fetch_all(MYSQLI_ASSOC);
  $q=db()->prepare('SELECT * FROM portfolio_images WHERE photographer_id=? ORDER BY id DESC LIMIT 30');$q->bind_param('i',$pid);$q->execute();$photos=$q->get_result()->fetch_all(MYSQLI_ASSOC);
  $q=db()->prepare('SELECT b.*,u.fullname,pa.name AS package_name,COALESCE(pm.status,\'pending\') AS payment_status FROM bookings b JOIN users u ON u.id=b.user_id JOIN packages pa ON pa.id=b.package_id LEFT JOIN payments pm ON pm.id=(SELECT MAX(id) FROM payments WHERE booking_id=b.id) WHERE b.photographer_id=? ORDER BY b.created_at DESC LIMIT 100');$q->bind_param('i',$pid);$q->execute();$bookings=$q->get_result()->fetch_all(MYSQLI_ASSOC);
 }
}else{
 $q=db()->prepare('SELECT b.*,p.studio_name,p.avatar_url,pa.name AS package_name,COALESCE(pm.status,\'pending\') AS payment_status FROM bookings b JOIN photographers p ON p.id=b.photographer_id JOIN packages pa ON pa.id=b.package_id LEFT JOIN payments pm ON pm.id=(SELECT MAX(id) FROM payments WHERE booking_id=b.id) WHERE b.user_id=? ORDER BY b.created_at DESC LIMIT 100');$q->bind_param('i',$uid);$q->execute();$bookings=$q->get_result()->fetch_all(MYSQLI_ASSOC);
}
$confirmed=count(array_filter($bookings,fn($b)=>in_array($b['status'],['confirmed','completed'],true)));
$pending=count(array_filter($bookings,fn($b)=>$b['status']==='pending'));
$page_title=($isPro?'Studio Dashboard':'My Dashboard').' | LensCraft';
$displayName=$isPro?($studio['studio_name']??$user['fullname']):$user['fullname'];
$avatar=$isPro?($studio['avatar_url']??''):'';
$cover=$isPro?($studio['cover_url']??''):'';
$upcoming=count(array_filter($bookings,fn($b)=>$b['booking_date']>=date('Y-m-d') && in_array($b['status'],['pending','confirmed'],true)));
$completed=count(array_filter($bookings,fn($b)=>$b['status']==='completed'));
$paid=count(array_filter($bookings,fn($b)=>$b['payment_status']==='paid'));
$slotDays=array_values(array_unique(array_column(array_filter($slots,static fn($slot)=>(int)$slot['is_booked']===0),'available_date')));
// Calendar uses all active reservations, not only the dashboard's latest 100 rows.
$calendarBookings=[];
if ($isPro && $studio) {
 $cq=db()->prepare("SELECT b.booking_date,b.start_time,b.end_time,b.status,b.booking_code,u.fullname,pa.name AS package_name FROM bookings b JOIN users u ON u.id=b.user_id JOIN packages pa ON pa.id=b.package_id WHERE b.photographer_id=? AND b.status IN ('pending','confirmed') AND b.booking_date>=DATE_SUB(CURDATE(), INTERVAL 12 MONTH) AND b.booking_date<DATE_ADD(CURDATE(), INTERVAL 24 MONTH) ORDER BY b.booking_date,b.start_time");
 $cq->bind_param('i',$pid);$cq->execute();$calendarBookings=$cq->get_result()->fetch_all(MYSQLI_ASSOC);
}
$bookedDays=array_values(array_unique(array_merge(array_column($calendarBookings,'booking_date'),array_column(array_filter($slots,static fn($slot)=>(int)$slot['is_booked']===1),'available_date'))));
require __DIR__.'/partials_header.php';
?>
<div class="lc-workspace" id="overview">
 <aside class="lc-side" aria-label="Dashboard navigation">
  <div class="lc-side-user"><div class="lc-side-avatar"><?php if($avatar): ?><img src="<?= e($avatar) ?>" alt="Profile picture"><?php else: ?><i class="fa-solid fa-camera"></i><?php endif; ?></div><strong><?= e($user['fullname']) ?></strong><span><?= $isPro?'Photographer':'Customer' ?></span></div>
  <div class="lc-side-caption">WORKSPACE</div>
  <a class="lc-side-link active" href="#overview"><i class="fa-solid fa-table-cells-large"></i> Dashboard</a>
  <a class="lc-side-link" href="account.php"><i class="fa-regular fa-user"></i> My profile</a>
  <?php if($isPro): ?>
  <a class="lc-side-link" href="#portfolio"><i class="fa-regular fa-images"></i> Portfolio <i class="fa-solid fa-angle-down lc-chevron"></i></a>
  <a class="lc-side-sub" href="#portfolio">All photos / Upload</a>
  <a class="lc-side-link" href="#packages"><i class="fa-solid fa-box-open"></i> Packages <i class="fa-solid fa-angle-down lc-chevron"></i></a>
  <a class="lc-side-sub" href="#package-add">Add new package</a>
  <a class="lc-side-link" href="#availability"><i class="fa-regular fa-calendar-days"></i> Available dates</a>
  <a class="lc-side-sub" href="#slot-add">Manage dates</a>
  <?php else: ?>
  <a class="lc-side-link" href="browse.php"><i class="fa-solid fa-magnifying-glass"></i> Explore studios</a>
  <a class="lc-side-link" href="cart.php"><i class="fa-solid fa-bag-shopping"></i> My cart</a>
  <?php endif; ?>
  <a class="lc-side-link" href="#bookings"><i class="fa-regular fa-clipboard"></i> <?= $isPro?'Client bookings':'My bookings' ?></a>
  <a class="lc-side-link" href="account.php"><i class="fa-solid fa-gear"></i> Settings</a>
  <?php if($isPro && $studio): ?><a class="lc-side-public" href="profile.php?id=<?= (int)$studio['id'] ?>">View public profile <i class="fa-solid fa-arrow-up-right-from-square"></i></a><?php endif; ?>
 </aside>
 <div class="lc-main">
  <div class="lc-hero" <?php if($cover): ?>style="background-image:linear-gradient(90deg,rgba(10,15,25,.54),rgba(10,15,25,.05)),url('<?= e($cover) ?>')"<?php endif; ?>>
   <div class="lc-hero-tag"><?= $isPro?'PHOTOGRAPHER WORKSPACE':'YOUR PHOTOGRAPHY JOURNEY' ?></div>
   <?php if($isPro): ?><a href="account.php" class="lc-cover-btn"><i class="fa-solid fa-camera"></i> Change cover photo</a><?php else: ?><a href="browse.php" class="lc-cover-btn">Discover photographers <i class="fa-solid fa-arrow-right"></i></a><?php endif; ?>
  </div>
  <div class="lc-identity">
   <div class="lc-identity-photo"><?php if($avatar): ?><img src="<?= e($avatar) ?>" alt="Studio avatar"><?php else: ?><i class="fa-solid fa-camera-retro"></i><?php endif; ?><?php if($isPro): ?><a href="account.php" title="Change profile photo" aria-label="Change profile photo"><i class="fa-solid fa-camera"></i></a><?php endif; ?></div>
   <div class="lc-identity-name"><span class="lc-eyebrow"><?= $isPro?'YOUR STUDIO':'YOUR ACCOUNT' ?></span><h1><?= e($displayName) ?> <i class="fa-solid fa-circle-check"></i></h1><p><i class="fa-solid fa-location-dot"></i> <?= e($isPro?($studio['location']??'Add your location'):$user['address']) ?> <?php if($isPro): ?> · <?= e($studio['category']??'Photography') ?><?php endif; ?></p></div>
   <div class="lc-metrics"><div><strong><?= count($bookings) ?></strong><span>Total bookings</span></div><div><strong><?= $completed ?></strong><span>Completed</span></div><div><strong><?= $upcoming ?></strong><span>Upcoming</span></div><div><strong><?= $isPro?count($photos):$paid ?></strong><span><?= $isPro?'Portfolio photos':'Paid bookings' ?></span></div></div>
  </div>
  <?php if($isPro && $studio): ?>
  <div class="lc-overview-grid">
   <section class="lc-card lc-info"><div class="lc-card-heading"><h2>Profile information</h2><a class="lc-small-primary" href="account.php"><i class="fa-solid fa-pen"></i> Edit</a></div><dl><div><dt>Studio name</dt><dd><?= e($studio['studio_name']) ?></dd></div><div><dt>Full name</dt><dd><?= e($user['fullname']) ?></dd></div><div><dt>Email</dt><dd><?= e($user['email']) ?></dd></div><div><dt>Phone</dt><dd><?= e($user['phone']) ?></dd></div><div><dt>Location</dt><dd><?= e($studio['location']) ?></dd></div><div><dt>Bio</dt><dd><?= e($studio['bio']?:'Add a studio biography from your profile settings.') ?></dd></div></dl></section>
   <section class="lc-card"><div class="lc-card-heading"><h2>Quick actions</h2></div><div class="lc-actions"><a href="#photo-add"><i class="fa-regular fa-images"></i> Upload photos</a><a href="#package-add"><i class="fa-solid fa-cube"></i> Add package</a><a href="#slot-add"><i class="fa-regular fa-calendar-plus"></i> Add available date</a><a href="#bookings"><i class="fa-regular fa-clipboard"></i> View bookings</a></div></section>
   <section class="lc-card lc-preview"><div class="lc-card-heading"><h2>Public profile preview</h2></div><div class="lc-preview-image" <?php if($cover): ?>style="background-image:url('<?= e($cover) ?>')"<?php endif; ?>></div><strong><?= e($studio['studio_name']) ?></strong><p><i class="fa-solid fa-location-dot"></i> <?= e($studio['location']) ?></p><p class="lc-preview-meta"><?= count($photos) ?> portfolio photos · <?= count($packages) ?> packages</p><a href="profile.php?id=<?= (int)$studio['id'] ?>" class="lc-wide-link">View public profile <i class="fa-solid fa-arrow-right"></i></a></section>
  </div>
  <div class="lc-main-grid">
   <section class="lc-card" id="portfolio"><div class="lc-card-heading"><h2>Portfolio photos <small><?= count($photos) ?></small></h2><a class="lc-small-primary" href="#photo-add">Add new photo <i class="fa-solid fa-plus"></i></a></div><div class="lc-gallery"><?php foreach(array_slice($photos,0,6) as $photo): ?><div class="lc-photo"><img src="<?= e($photo['image_path']) ?>" alt="<?= e($photo['caption']) ?>" loading="lazy"><form method="post" action="studio_manage.php" onsubmit="return confirm('Remove this photo?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete_photo"><input type="hidden" name="id" value="<?= (int)$photo['id'] ?>"><button title="Remove photo" aria-label="Remove photo"><i class="fa-solid fa-trash"></i></button></form></div><?php endforeach; ?><?php if(!$photos): ?><div class="lc-empty"><i class="fa-regular fa-images"></i><p>No portfolio photos yet. Upload your best work below.</p></div><?php endif; ?></div><a class="lc-wide-link" href="#photo-add">Manage portfolio <i class="fa-solid fa-arrow-right"></i></a></section>
   <section class="lc-card" id="packages"><div class="lc-card-heading"><h2>Manage packages <small><?= count($packages) ?></small></h2><a class="lc-small-primary" href="#package-add">Add new package <i class="fa-solid fa-plus"></i></a></div><div class="lc-package-list"><?php foreach(array_slice($packages,0,5) as $pack): ?><div class="lc-package"><div class="lc-package-icon"><i class="fa-solid fa-camera"></i></div><div class="lc-package-name"><strong><?= e($pack['name']) ?></strong><small><?= e(substr((string)$pack['description'],0,48)) ?></small></div><strong><?= money((float)$pack['price']) ?></strong><span class="lc-status-good">Active</span><a href="#edit-package-<?= (int)$pack['id'] ?>" title="Edit package"><i class="fa-solid fa-pen"></i></a></div><?php endforeach; ?><?php if(!$packages): ?><div class="lc-empty">Create a package to start accepting bookings.</div><?php endif; ?></div><a class="lc-wide-link" href="#package-add">View and edit packages <i class="fa-solid fa-arrow-right"></i></a></section>
  </div>
  <div class="lc-bottom-grid">
   <section class="lc-card" id="availability"><div class="lc-card-heading"><h2>Availability calendar</h2><a class="lc-small-primary" href="#slot-add">Add date</a></div><div class="lc-calendar" data-available="<?= e(json_encode($slotDays)) ?>" data-booked="<?= e(json_encode($bookedDays)) ?>" data-bookings="<?= e(json_encode($calendarBookings,JSON_INVALID_UTF8_SUBSTITUTE)) ?>" data-sync="calendar_feed.php"><div class="lc-calendar-nav"><button type="button" data-cal-prev aria-label="Previous month"><i class="fa-solid fa-chevron-left"></i></button><strong data-cal-title></strong><button type="button" data-cal-next aria-label="Next month"><i class="fa-solid fa-chevron-right"></i></button></div><div class="lc-calendar-days" data-cal-days></div><div class="lc-calendar-detail" data-cal-detail aria-live="polite">Select a date to view booking details.</div><p class="lc-calendar-sync" data-cal-sync>Booking dates refresh automatically every 20 seconds.</p></div><div class="lc-legend"><span><b class="lc-dot available"></b> Available</span><span><b class="lc-dot booked"></b> Booked</span><span><b class="lc-dot"></b> Past date</span></div></section>
   <section class="lc-card"><div class="lc-card-heading"><h2>Upcoming bookings</h2><a href="#bookings">View all →</a></div><div class="lc-booking-list"><?php $shown=0;foreach($bookings as $b):if($b['booking_date']<date('Y-m-d')||!in_array($b['status'],['pending','confirmed'],true))continue;$shown++;if($shown>4)break; ?><div class="lc-booking-row"><div class="lc-booking-icon"><i class="fa-regular fa-calendar-check"></i></div><div><strong><?= e($b['fullname']) ?></strong><small><?= e($b['package_name']) ?></small><small><?= e($b['booking_date'].' · '.substr($b['start_time'],0,5)) ?></small></div><span class="lc-status-good"><?= e($b['status']) ?></span></div><?php endforeach; ?><?php if(!$shown): ?><div class="lc-empty">No upcoming bookings yet.</div><?php endif; ?></div></section>
   <section class="lc-card"><div class="lc-card-heading"><h2>Studio insights</h2></div><div class="lc-insight"><span><i class="fa-solid fa-camera"></i> Portfolio photos</span><strong><?= count($photos) ?></strong></div><div class="lc-insight"><span><i class="fa-solid fa-box"></i> Packages published</span><strong><?= count($packages) ?></strong></div><div class="lc-insight"><span><i class="fa-solid fa-calendar-check"></i> Upcoming slots</span><strong><?= count($slots) ?></strong></div><div class="lc-insight"><span><i class="fa-solid fa-receipt"></i> Paid bookings</span><strong><?= $paid ?></strong></div><p class="lc-muted-note">Insights show your real database records, not sample ratings or invented reviews.</p></section>
  </div>
  <div class="lc-management">
   <section class="lc-card" id="photo-add"><div class="lc-card-heading"><h2><i class="fa-solid fa-cloud-arrow-up"></i> Upload portfolio photo</h2></div><form class="lc-form" method="post" action="studio_manage.php" enctype="multipart/form-data"><?= csrf_field() ?><input type="hidden" name="action" value="add_photo"><label>Photo (JPG, PNG, WEBP · max 5 MB)<input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><label>Photo caption<input name="caption" maxlength="255" placeholder="A beautiful wedding moment"></label><button class="btn btn-primary">Upload photo</button></form></section>
   <section class="lc-card" id="package-add"><div class="lc-card-heading"><h2><i class="fa-solid fa-cube"></i> Create new package</h2></div><form class="lc-form" method="post" action="studio_manage.php"><?= csrf_field() ?><input type="hidden" name="action" value="add_package"><label>Package name<input name="package_name" maxlength="120" required placeholder="Signature wedding package"></label><label>What's included?<textarea name="package_description" rows="3" maxlength="2000"></textarea></label><div class="lc-input-row"><label>Price (LKR)<input type="number" name="package_price" min="1" step="0.01" required></label><label>Duration (hours)<input type="number" name="duration_hours" min="0.5" max="48" step="0.5" value="2" required></label></div><button class="btn btn-primary">Publish package</button></form></section>
   <section class="lc-card" id="day-blocking"><div class="lc-card-heading"><h2>Mark a whole day red / green</h2></div><p class="lc-muted-note">All future dates are green by default. Block a date to make it red. Unblock to restore green. Days with active bookings cannot be unblocked through this form.</p><form method="post" action="studio_manage.php" class="lc-form"><?= csrf_field() ?><label>Choose date<input type="date" name="block_date" min="<?= date('Y-m-d') ?>" required></label><div style="display:flex;gap:10px;flex-wrap:wrap"><button type="submit" class="btn btn-primary" name="action" value="block_day">Mark red (blocked)</button><button type="submit" class="btn btn-ghost" name="action" value="unblock_day">Mark green (available)</button></div></form></section>
   <section class="lc-card" id="slot-add"><div class="lc-card-heading"><h2><i class="fa-regular fa-calendar-plus"></i> Manage availability</h2></div><form class="lc-form" method="post" action="studio_manage.php"><?= csrf_field() ?><input type="hidden" name="action" value="add_slot"><label>Available date<input type="date" name="available_date" min="<?= date('Y-m-d') ?>" required></label><div class="lc-input-row"><label>From<input type="time" name="start_time" required></label><label>To<input type="time" name="end_time" required></label></div><button class="btn btn-primary">Publish time slot</button></form><div class="lc-slot-list"><?php foreach($slots as $slot): ?><div><span><?= e($slot['available_date'].' · '.substr($slot['start_time'],0,5).'–'.substr($slot['end_time'],0,5)) ?></span><span class="lc-slot-status <?= (int)$slot['is_booked']===1?'blocked':'open' ?>"><?= (int)$slot['is_booked']===1?'Blocked':'Available' ?></span><form method="post" action="studio_manage.php"><?= csrf_field() ?><input type="hidden" name="action" value="toggle_slot"><input type="hidden" name="id" value="<?= (int)$slot['id'] ?>"><button class="lc-slot-action" type="submit"><?= (int)$slot['is_booked']===1?'Mark available':'Mark blocked' ?></button></form><form method="post" action="studio_manage.php" onsubmit="return confirm('Remove this slot?')"><?= csrf_field() ?><input type="hidden" name="action" value="delete_slot"><input type="hidden" name="id" value="<?= (int)$slot['id'] ?>"><button aria-label="Remove slot"><i class="fa-solid fa-trash"></i></button></form></div><?php endforeach; ?><?php if(!$slots): ?><p class="lc-muted-note">All future dates are available by default (09:00–18:00).</p><?php endif; ?></div></section>
   <section class="lc-card"><div class="lc-card-heading"><h2><i class="fa-solid fa-sliders"></i> Edit existing packages</h2></div><?php foreach($packages as $pack): ?><details class="lc-package-editor" id="edit-package-<?= (int)$pack['id'] ?>"><summary><?= e($pack['name']) ?> <span><?= money((float)$pack['price']) ?> <i class="fa-solid fa-chevron-down"></i></span></summary><form class="lc-form" method="post" action="studio_manage.php"><?= csrf_field() ?><input type="hidden" name="action" value="edit_package"><input type="hidden" name="id" value="<?= (int)$pack['id'] ?>"><label>Name<input name="package_name" maxlength="120" value="<?= e($pack['name']) ?>" required></label><label>Description<textarea name="package_description" maxlength="2000" rows="3"><?= e($pack['description']) ?></textarea></label><div class="lc-input-row"><label>Price<input type="number" name="package_price" min="1" step="0.01" value="<?= e((string)$pack['price']) ?>" required></label><label>Duration<input type="number" name="duration_hours" min="0.5" max="48" step="0.5" value="<?= e((string)$pack['duration_hours']) ?>" required></label></div><button class="btn btn-primary">Save changes</button></form><form method="post" action="studio_manage.php" onsubmit="return confirm('Delete this package? Packages with bookings cannot be removed.')"><?= csrf_field() ?><input type="hidden" name="action" value="delete_package"><input type="hidden" name="id" value="<?= (int)$pack['id'] ?>"><button class="lc-danger-btn">Delete package</button></form></details><?php endforeach; ?><?php if(!$packages): ?><p class="lc-muted-note">No packages to edit.</p><?php endif; ?></section>
  </div>
  <?php else: ?>
  <div class="lc-customer-grid"><section class="lc-card"><div class="lc-card-heading"><h2>Welcome to your account</h2><a class="lc-small-primary" href="account.php">Edit details</a></div><p class="lc-muted-note">Discover photography professionals, compare packages and manage all your bookings in one place.</p><div class="lc-actions"><a href="browse.php"><i class="fa-solid fa-magnifying-glass"></i> Browse photographers</a><a href="cart.php"><i class="fa-solid fa-bag-shopping"></i> View cart</a><a href="#bookings"><i class="fa-regular fa-calendar-check"></i> My bookings</a><a href="account.php"><i class="fa-regular fa-user"></i> Account settings</a></div></section><section class="lc-card"><div class="lc-card-heading"><h2>Booking overview</h2></div><div class="lc-insight"><span>Total bookings</span><strong><?= count($bookings) ?></strong></div><div class="lc-insight"><span>Upcoming</span><strong><?= $upcoming ?></strong></div><div class="lc-insight"><span>Paid</span><strong><?= $paid ?></strong></div><a class="lc-wide-link" href="browse.php">Find a photographer →</a></section></div>
  <?php endif; ?>
  <section class="lc-card lc-bookings-table" id="bookings"><div class="lc-card-heading"><h2><?= $isPro?'All client bookings':'My bookings & payments' ?></h2><span><?= count($bookings) ?> records</span></div><div class="table-wrap"><table><thead><tr><th>Booking</th><th><?= $isPro?'Customer':'Photographer' ?></th><th>Date / time</th><th>Amount</th><th>Payment</th><th>Status / action</th></tr></thead><tbody><?php foreach($bookings as $b): ?><tr><td><strong><?= e($b['booking_code']) ?></strong><small><?= e($b['package_name']) ?></small></td><td><?= e($isPro?$b['fullname']:$b['studio_name']) ?></td><td><?= e($b['booking_date']) ?><small><?= e(substr($b['start_time'],0,5).' – '.substr($b['end_time'],0,5)) ?></small></td><td><?= money((float)$b['amount']) ?></td><td><span class="status <?= e($b['payment_status']) ?>"><?= e(ucfirst($b['payment_status'])) ?></span></td><td><span class="status <?= e($b['status']) ?>"><?= e(ucfirst($b['status'])) ?></span><?php if(!$isPro && $b['payment_status']==='pending' && $b['status']==='pending'): ?><br><a href="checkout.php?booking=<?= (int)$b['id'] ?>">Continue payment →</a><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$bookings): ?><tr><td colspan="6" class="lc-empty">No bookings yet.</td></tr><?php endif; ?></tbody></table></div></section>
 </div>
</div>
<script src="dashboard.js" defer></script>
<?php require __DIR__.'/partials_footer.php'; ?>
