<?php
declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';
$page_title = 'LensCraft | Your Story, Beautifully Captured';
$featured = [];
$portfolio = [];
$counts = ['photographers'=>0,'packages'=>0];
try {
    $rs = db()->query("SELECT p.id,p.studio_name,p.category,p.location,p.bio,p.cover_url,p.avatar_url,p.rating,p.base_price, MIN(pa.price) AS min_price, COUNT(DISTINCT pa.id) AS package_count FROM photographers p LEFT JOIN packages pa ON pa.photographer_id=p.id AND pa.is_active=1 AND pa.stock_qty>0 WHERE p.is_active=1 GROUP BY p.id,p.studio_name,p.category,p.location,p.bio,p.cover_url,p.avatar_url,p.rating,p.base_price ORDER BY p.rating DESC,p.id DESC LIMIT 6");
    while ($row = $rs->fetch_assoc()) $featured[] = $row;
    $rs = db()->query("SELECT pi.image_path,pi.caption,p.id AS photographer_id,p.studio_name,p.category FROM portfolio_images pi JOIN photographers p ON p.id=pi.photographer_id WHERE p.is_active=1 ORDER BY pi.created_at DESC,pi.id DESC LIMIT 8");
    while ($row = $rs->fetch_assoc()) $portfolio[] = $row;
    $counts['photographers'] = (int) db()->query("SELECT COUNT(*) n FROM photographers WHERE is_active=1")->fetch_assoc()['n'];
    $counts['packages'] = (int) db()->query("SELECT COUNT(*) n FROM packages pa JOIN photographers p ON p.id=pa.photographer_id WHERE p.is_active=1 AND pa.is_active=1 AND pa.stock_qty>0")->fetch_assoc()['n'];
} catch (Throwable $ex) {
    error_log('Home page data error: '.$ex->getMessage());
}
$categories = [
    ['name'=>'Wedding','icon'=>'fa-ring','desc'=>'Timeless moments, beautifully told.','photo'=>'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=85'],
    ['name'=>'Portrait','icon'=>'fa-user','desc'=>'Every expression has a story.','photo'=>'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85'],
    ['name'=>'Event','icon'=>'fa-champagne-glasses','desc'=>'The energy you want to remember.','photo'=>'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85'],
    ['name'=>'Fashion','icon'=>'fa-wand-magic-sparkles','desc'=>'A bold creative point of view.','photo'=>'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=85']
];
require_once __DIR__ . '/partials_header.php';
?>
<div class="lc-home">
<section class="lc-hero">
 <div class="lc-hero-bg" aria-hidden="true"></div>
 <div class="lc-hero-glow" aria-hidden="true"></div>
 <div class="container lc-hero-inner">
  <div class="lc-hero-copy">
   <span class="lc-kicker"><span class="lc-kicker-dot"></span> THE ART OF REMEMBERING</span>
   <h1>Every moment<br>deserves to be <span>extraordinary.</span></h1>
   <p>Find talented photographers, explore their real work, and book the perfect creative for your next unforgettable moment.</p>
   <div class="lc-hero-actions"><a href="browse.php" class="btn btn-primary lc-hero-button">Explore photographers <i class="fa-solid fa-arrow-up-right-from-square"></i></a><a href="#how-it-works" class="lc-watch"><span><i class="fa-solid fa-play"></i></span> How it works</a></div>
   <div class="lc-hero-trust"><div class="lc-avatar-stack" aria-hidden="true"><span><i class="fa-solid fa-camera"></i></span><span><i class="fa-solid fa-heart"></i></span><span><i class="fa-solid fa-star"></i></span></div><div><strong><?= number_format($counts['photographers']) ?> photographers</strong><small>Discover creatives across Sri Lanka</small></div></div>
  </div>
  <div class="lc-hero-visual" aria-hidden="true"><div class="lc-visual-frame lc-visual-main"><img src="https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1100&q=90" alt=""></div><div class="lc-visual-frame lc-visual-small"><img src="https://images.unsplash.com/photo-1529636798458-92182e662485?auto=format&fit=crop&w=600&q=85" alt=""></div><div class="lc-floating-label"><i class="fa-solid fa-camera-retro"></i><span>Make memories<br><strong>last forever.</strong></span></div><div class="lc-visual-outline"></div></div>
 </div>
 <div class="container lc-search-wrap"><form action="browse.php" method="get" class="lc-search-form"><div class="lc-search-heading"><i class="fa-solid fa-sliders"></i> FIND YOUR PERFECT MATCH <span>Search our photographer directory</span></div><div class="lc-search-fields"><label><small><i class="fa-solid fa-location-dot"></i> LOCATION</small><input name="location" placeholder="City or location"></label><label><small><i class="fa-solid fa-camera"></i> CATEGORY</small><select name="category"><option value="">All photography styles</option><?php foreach($categories as $cat): ?><option value="<?= e($cat['name']) ?>"><?= e($cat['name']) ?></option><?php endforeach; ?><option value="Commercial">Commercial</option></select></label><label><small><i class="fa-regular fa-calendar"></i> YOUR DATE</small><input type="date" name="date" min="<?= date('Y-m-d') ?>" aria-label="Preferred date"></label><button class="btn btn-primary lc-search-submit" type="submit"><i class="fa-solid fa-magnifying-glass"></i> Find photographers</button></div></form></div>
</section>
<section class="lc-section lc-category-section container" id="categories"><div class="lc-section-top"><div><span class="lc-overline">EXPLORE YOUR STYLE</span><h2>Photography for <em>every story.</em></h2><p>From once-in-a-lifetime celebrations to everyday magic.</p></div><a class="lc-inline-link" href="browse.php">Explore all styles <i class="fa-solid fa-arrow-right"></i></a></div><div class="lc-category-grid"><?php foreach($categories as $cat): ?><a class="lc-category" href="browse.php?category=<?= urlencode($cat['name']) ?>"><img loading="lazy" src="<?= e($cat['photo']) ?>" alt="<?= e($cat['name']) ?> photography"><div class="lc-category-shade"></div><span class="lc-category-icon"><i class="fa-solid <?= e($cat['icon']) ?>"></i></span><div class="lc-category-copy"><h3><?= e($cat['name']) ?></h3><p><?= e($cat['desc']) ?></p></div><span class="lc-category-arrow"><i class="fa-solid fa-arrow-up-right-from-square"></i></span></a><?php endforeach; ?></div></section>
<section class="lc-section lc-featured-section"><div class="container"><div class="lc-section-top"><div><span class="lc-overline">HANDPICKED CREATIVES</span><h2>Meet your next <em>photographer.</em></h2><p>Explore real profiles and choose the right style for you.</p></div><a class="lc-inline-link" href="browse.php">Browse all photographers <i class="fa-solid fa-arrow-right"></i></a></div><?php if($featured): ?><div class="lc-featured-grid"><?php foreach($featured as $p): ?><article class="lc-photographer"><a class="lc-photographer-image" href="profile.php?id=<?= (int)$p['id'] ?>"><img loading="lazy" src="<?= e($p['cover_url'] ?: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=1000&q=85') ?>" alt="<?= e($p['studio_name']) ?> portfolio"><span class="lc-image-category"><?= e($p['category']) ?></span></a><div class="lc-photographer-info"><div class="lc-photographer-title"><div class="lc-photographer-avatar"><?php if(!empty($p['avatar_url'])): ?><img loading="lazy" src="<?= e($p['avatar_url']) ?>" alt=""><?php else: ?><i class="fa-solid fa-camera"></i><?php endif; ?></div><div><h3><?= e($p['studio_name']) ?></h3><p><i class="fa-solid fa-location-dot"></i> <?= e($p['location']) ?></p></div></div><div class="lc-photographer-foot"><div><small>STARTING FROM</small><strong><?= money((float)($p['min_price'] ?? $p['base_price'])) ?></strong></div><a class="lc-profile-button" href="profile.php?id=<?= (int)$p['id'] ?>" aria-label="View <?= e($p['studio_name']) ?> profile"><i class="fa-solid fa-arrow-right"></i></a></div></div></article><?php endforeach; ?></div><?php else: ?><div class="lc-empty"><i class="fa-solid fa-camera-retro"></i><h3>Great stories start here.</h3><p>Photographers will appear here as soon as their profiles are published.</p><a href="register.php" class="btn btn-primary">Join as a photographer</a></div><?php endif; ?></div></section>
<section class="lc-section lc-how container" id="how-it-works"><div class="lc-how-lead"><span class="lc-overline">SIMPLE FROM START TO FINISH</span><h2>Your perfect shoot,<br><em>just a few clicks away.</em></h2><p>Less time planning. More time making memories.</p><a href="browse.php" class="btn btn-primary">Start exploring <i class="fa-solid fa-arrow-right"></i></a></div><div class="lc-how-steps"><div><span>01 <i class="fa-solid fa-magnifying-glass"></i></span><h3>Find your creative</h3><p>Browse portfolios, locations and packages to find your style.</p></div><div><span>02 <i class="fa-regular fa-calendar-check"></i></span><h3>Pick your moment</h3><p>Choose a package and a suitable available date and time.</p></div><div><span>03 <i class="fa-solid fa-credit-card"></i></span><h3>Book with confidence</h3><p>Review your booking and proceed to the configured payment gateway.</p></div></div></section>
<?php if($portfolio): ?><section class="lc-section lc-gallery-section"><div class="container"><div class="lc-section-top"><div><span class="lc-overline">REAL WORK. REAL MOMENTS.</span><h2>Stories through <em>the lens.</em></h2><p>Fresh photographs shared by photographers on LensCraft.</p></div><a href="browse.php" class="lc-inline-link">Find your inspiration <i class="fa-solid fa-arrow-right"></i></a></div><div class="lc-mosaic"><?php foreach($portfolio as $photo): ?><a href="profile.php?id=<?= (int)$photo['photographer_id'] ?>" class="lc-mosaic-photo"><img loading="lazy" src="<?= e($photo['image_path']) ?>" alt="<?= e($photo['caption'] ?: $photo['studio_name']) ?>"><span><?= e($photo['studio_name']) ?> <i class="fa-solid fa-arrow-up-right-from-square"></i></span></a><?php endforeach; ?></div></div></section><?php endif; ?>
<section class="lc-section lc-cta container"><div class="lc-cta-image" aria-hidden="true"></div><div class="lc-cta-content"><span class="lc-overline">FOR PHOTOGRAPHERS</span><h2>Your talent deserves<br><em>to be discovered.</em></h2><p>Build your portfolio, publish packages, manage available dates and connect with customers looking for your work.</p><a href="register.php" class="btn btn-primary">Create your photographer account <i class="fa-solid fa-arrow-right"></i></a></div></section>
</div>
<?php require_once __DIR__ . '/partials_footer.php'; ?>
